### ISSUE TITLE
IRAF crashes DS9 when attempting to display image while using DS9 Version 7.3.2

### ISSUE THREAD

**Issue by steelewool** [olebole/iraf-v216#27]
This was observed in the merge-all branch with the SHA of 48fb222eb9016f093a1b5cfff18f59b22ed18e40

When using version 7.6 b5 of DS9 the images are displayed and iraf isn't crashing. 

Even if the IRAF s/w won't play nicely with the older DS9, having the program crash isn't acceptable and should be considered a bug.

So, after starting the 7.3.2 version of DS9 and then running IRAF:

ecl> display dev$pix
frame to be written into (1:4) (1): 1
ERROR: Cannot open device (node!imtool,,512,512)
ecl>

**Comment by olebole** [comment]
It works at least with DS9 version 7.5 (which is the one in Debian/Raspbian release). I will test with 7.3.2 later.

**Comment by olebole** [comment]
I cannot reproduce it with 7.3.2. I just downloaded this version from the [ds9 archive](http://ds9.si.edu/archive/linux64/) unpackaged it, and did
```
$ export IMTDEV=inet:5137
$ ./ds9&
[1] 21209
$ cl
[...]
vocl> display dev$pix
frame to be written into (1:16) (1): 
z1=35. z2=346.0218
```

The DS9 display now shows the the image, without crashing. Using latest Debian (testing), with a just-compiled `merge-all`branch.

Could you give a link to the discussion of the topic in the forum?

**Comment by steelewool** [comment]
I'll find that discussion and repeat the experiment on my linux64 with the
merge-all branch. BTW, I was seeing the problem of the ds9 crashing on my
raspberry pi on the porting branch.

Rob

**Comment by olebole** [comment]
Ah, OK, I can reproduce it when compiling from Jessie and using the ds9 that comes with Jessie.
At least I had however some misunderstanding here: it is _not_ IRAF that crashed, but DS9, and specifically the one that came with Jessie.
That was a real issue with the Debian version (not the upstream one); see Debian bug report [#805461](https://bugs.debian.org/805641). This is nothing that can be solved within IRAF.
The Problem is fixed with the DS9 version that comes with Stretch; so it is probably the best to update to Stretch (which is also available as Raspbian, BTW).

**Comment by olebole** [comment]
@steelewool could you confirm that it was a DS9 crash what you have observed? In this case, I would close the issue.

**Comment by steelewool** [comment]
Just to finish thing up on this, it was an older version of DS9 that I used that crashed when I attempted to display an image. We should close out this item based on this. So the steps I've taken with the porting branch:
- grabbed stretch and updated my Raspberry Pi OS
  - As my Pi crashed in my first attempt and hung I had to build the OS from the ground up
- Cloned the latest iraf-v216 from Ole's repository
- Before attempting build the IRAF s/w I installed curl, ncurses, and expat libraries first (libcurl4-gnutls-dev, libncurses5-dev, libexpat1-dev packages).
- Built the IRAF s/w
- Installed DS9 using the synaptic package manager.
- Sourced ~/.iraf/setup.cs
- Was able to run ecl
- Ran test cases, with the results:
ecl.e: README.md ...xsa
ecl.e: files.md ......
ecl.e: images.imcoords.md ...........
ecl.e: images.imfilter.md ..............
ecl.e: images.imfit.md ...
ecl.e: images.imgeom.md ........
ecl.e: images.immatch.md .x.
ecl.e: lists.md .......
ecl.e: nttools.md ..............
ecl.e: numerical-recipes.md ..........
ecl.e: programming.md .........
ecl.e: testproc.md ........................
Test summary:    111 passed, 2 skipped, 2 xfailed

**Comment by olebole** [comment]
So, does iraf+ds9 work with Raspberry Stretch?

**Comment by steelewool** [comment]
Yes, work excellent.

On November 25, 2017, at 12:16 PM, Ole Streicher <notifications@github.com> wrote:

So, does iraf+ds9 work with Raspberry Stretch?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/olebole/iraf-v216","title":"olebole/iraf-v216","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/olebole/iraf-v216">https://github.com/olebole/iraf-v216</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@olebole in #27: So, does iraf+ds9 work with Raspberry Stretch?"}],"action":{"name":"View Issue","url":"<a href="https://github.com/olebole/iraf-v216/issues/27#issuecomment-346963476">https://github.com/olebole/iraf-v216/issues/27#issuecomment-346963476</a>"}}}
